export const COLLECTION_IS_LOADING = "USERS_IS_LOADING";
export const RECEIVED_COLLECTION = "RECEIVED_USERS";
export const RECEIVED_MODEL = "RECEIVED_USER";
export const REMOVED_MODEL = "REMOVED_MODEL";
export const UPDATE_COLLECTION_QUERY = "UPDATE_USERS_QUERY";

export default {
    COLLECTION_IS_LOADING,
    RECEIVED_COLLECTION,
    RECEIVED_MODEL,
    REMOVED_MODEL,
    UPDATE_COLLECTION_QUERY
};
