export const MAIN_HEADER_USER_PANEL_TOGGLE = "MAIN_HEADER_USER_PANEL_TOGGLE";
export const CONTROL_SIDEBAR_TOGGLE = "CONTROL_SIDEBAR_TOGGLE";
export const MAIN_SIDEBAR_TOGGLE = "MAIN_SIDEBAR_TOGGLE";

export default {
    CONTROL_SIDEBAR_TOGGLE,
    MAIN_SIDEBAR_TOGGLE,
    MAIN_HEADER_USER_PANEL_TOGGLE
};
